// ============================================
// PORTFOLYO.SE - 50 CV Templates
// Enterprise-grade CV designs for professionals
// ============================================

export interface CVTemplateDefinition {
  id: string;
  name: string;
  description: string;
  category: 'modern' | 'classic' | 'creative' | 'minimal' | 'professional' | 'tech' | 'executive';
  tier: 'free' | 'starter' | 'pro';
  preview: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
    muted: string;
  };
  fonts: {
    heading: string;
    body: string;
  };
  layout: 'single-column' | 'two-column' | 'sidebar' | 'classic' | 'timeline' | 'infographic';
  atsOptimized: boolean;
  popular?: boolean;
  new?: boolean;
}

export const CV_TEMPLATES: CVTemplateDefinition[] = [
  // =====================
  // FREE TIER (5 templates)
  // =====================
  {
    id: 'cv-minimal-clean',
    name: 'Minimal Clean',
    description: 'Ren och enkel design som låter innehållet tala',
    category: 'minimal',
    tier: 'free',
    preview: '/cv/minimal-clean.png',
    colors: {
      primary: '#000000',
      secondary: '#666666',
      accent: '#333333',
      background: '#ffffff',
      text: '#000000',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'single-column',
    atsOptimized: true,
    popular: true,
  },
  {
    id: 'cv-professional-blue',
    name: 'Professional Blue',
    description: 'Klassisk professionell stil med blå accenter',
    category: 'professional',
    tier: 'free',
    preview: '/cv/professional-blue.png',
    colors: {
      primary: '#1e40af',
      secondary: '#3b82f6',
      accent: '#60a5fa',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
    popular: true,
  },
  {
    id: 'cv-modern-dark',
    name: 'Modern Dark',
    description: 'Modernt mörkt tema för tech-profiler',
    category: 'modern',
    tier: 'free',
    preview: '/cv/modern-dark.png',
    colors: {
      primary: '#ff4d4d',
      secondary: '#888888',
      accent: '#ff6666',
      background: '#0a0a0a',
      text: '#ffffff',
      muted: '#a1a1aa',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'single-column',
    atsOptimized: false,
    popular: true,
  },
  {
    id: 'cv-corporate-classic',
    name: 'Corporate Classic',
    description: 'Tidlös design för företagsmiljöer',
    category: 'classic',
    tier: 'free',
    preview: '/cv/corporate-classic.png',
    colors: {
      primary: '#1a365d',
      secondary: '#2c5282',
      accent: '#4299e1',
      background: '#ffffff',
      text: '#1a202c',
      muted: '#718096',
    },
    fonts: { heading: 'Georgia, serif', body: 'Arial, sans-serif' },
    layout: 'classic',
    atsOptimized: true,
  },
  {
    id: 'cv-simple-elegant',
    name: 'Simple Elegant',
    description: 'Elegant enkelhet med serif-typografi',
    category: 'minimal',
    tier: 'free',
    preview: '/cv/simple-elegant.png',
    colors: {
      primary: '#1a1a1a',
      secondary: '#4a4a4a',
      accent: '#7c7c7c',
      background: '#fafaf8',
      text: '#1a1a1a',
      muted: '#6b7280',
    },
    fonts: { heading: 'Playfair Display, serif', body: 'Lora, serif' },
    layout: 'single-column',
    atsOptimized: true,
  },

  // =====================
  // STARTER TIER (20 templates)
  // =====================
  {
    id: 'cv-creative-gradient',
    name: 'Creative Gradient',
    description: 'Kreativ design med moderna gradienter',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/creative-gradient.png',
    colors: {
      primary: '#8b5cf6',
      secondary: '#ec4899',
      accent: '#a78bfa',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
    new: true,
  },
  {
    id: 'cv-tech-mono',
    name: 'Tech Mono',
    description: 'Monospace-estetik för utvecklare',
    category: 'tech',
    tier: 'starter',
    preview: '/cv/tech-mono.png',
    colors: {
      primary: '#00ff00',
      secondary: '#00aa00',
      accent: '#22c55e',
      background: '#0d0d0d',
      text: '#00ff00',
      muted: '#86efac',
    },
    fonts: { heading: 'JetBrains Mono, monospace', body: 'JetBrains Mono, monospace' },
    layout: 'single-column',
    atsOptimized: false,
    popular: true,
  },
  {
    id: 'cv-elegant-gold',
    name: 'Elegant Gold',
    description: 'Lyxig design med guldaccenter',
    category: 'executive',
    tier: 'starter',
    preview: '/cv/elegant-gold.png',
    colors: {
      primary: '#d4af37',
      secondary: '#b8860b',
      accent: '#e6c75a',
      background: '#fffef7',
      text: '#1a1a1a',
      muted: '#78716c',
    },
    fonts: { heading: 'Cormorant Garamond, serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-startup-fresh',
    name: 'Startup Fresh',
    description: 'Fräsch och modern för startups',
    category: 'modern',
    tier: 'starter',
    preview: '/cv/startup-fresh.png',
    colors: {
      primary: '#06b6d4',
      secondary: '#22d3ee',
      accent: '#67e8f9',
      background: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
    new: true,
  },
  {
    id: 'cv-academic',
    name: 'Academic',
    description: 'Akademisk och formell för forskare',
    category: 'classic',
    tier: 'starter',
    preview: '/cv/academic.png',
    colors: {
      primary: '#1e3a5f',
      secondary: '#2c5282',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1a202c',
      muted: '#6b7280',
    },
    fonts: { heading: 'Times New Roman, serif', body: 'Times New Roman, serif' },
    layout: 'classic',
    atsOptimized: true,
  },
  {
    id: 'cv-designer-portfolio',
    name: 'Designer Portfolio',
    description: 'Kreativ layout för designers',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/designer-portfolio.png',
    colors: {
      primary: '#f472b6',
      secondary: '#ec4899',
      accent: '#f9a8d4',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#9ca3af',
    },
    fonts: { heading: 'Space Grotesk, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-nordic-light',
    name: 'Nordic Light',
    description: 'Skandinavisk minimalism',
    category: 'minimal',
    tier: 'starter',
    preview: '/cv/nordic-light.png',
    colors: {
      primary: '#64748b',
      secondary: '#94a3b8',
      accent: '#cbd5e1',
      background: '#f8fafc',
      text: '#334155',
      muted: '#94a3b8',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'single-column',
    atsOptimized: true,
  },
  {
    id: 'cv-bold-statement',
    name: 'Bold Statement',
    description: 'Gör ett starkt intryck med färg',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/bold-statement.png',
    colors: {
      primary: '#ef4444',
      secondary: '#dc2626',
      accent: '#f87171',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Archivo Black, sans-serif', body: 'Inter, sans-serif' },
    layout: 'single-column',
    atsOptimized: false,
  },
  {
    id: 'cv-consultant',
    name: 'Consultant',
    description: 'Professionellt för konsulter',
    category: 'professional',
    tier: 'starter',
    preview: '/cv/consultant.png',
    colors: {
      primary: '#0284c7',
      secondary: '#0369a1',
      accent: '#38bdf8',
      background: '#ffffff',
      text: '#1e293b',
      muted: '#64748b',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
    popular: true,
  },
  {
    id: 'cv-developer',
    name: 'Developer',
    description: 'Optimerat för utvecklare',
    category: 'tech',
    tier: 'starter',
    preview: '/cv/developer.png',
    colors: {
      primary: '#22c55e',
      secondary: '#16a34a',
      accent: '#4ade80',
      background: '#0f172a',
      text: '#e2e8f0',
      muted: '#94a3b8',
    },
    fonts: { heading: 'JetBrains Mono, monospace', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Lugnande blåa toner',
    category: 'modern',
    tier: 'starter',
    preview: '/cv/ocean-breeze.png',
    colors: {
      primary: '#0ea5e9',
      secondary: '#0284c7',
      accent: '#38bdf8',
      background: '#f0f9ff',
      text: '#0c4a6e',
      muted: '#7dd3fc',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-forest-green',
    name: 'Forest Green',
    description: 'Naturinspirerat grönt tema',
    category: 'professional',
    tier: 'starter',
    preview: '/cv/forest-green.png',
    colors: {
      primary: '#166534',
      secondary: '#22c55e',
      accent: '#4ade80',
      background: '#ffffff',
      text: '#14532d',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-sunset-warm',
    name: 'Sunset Warm',
    description: 'Varma färger för personligt intryck',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/sunset-warm.png',
    colors: {
      primary: '#f97316',
      secondary: '#fb923c',
      accent: '#fdba74',
      background: '#fffbf5',
      text: '#431407',
      muted: '#9a3412',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-midnight-purple',
    name: 'Midnight Purple',
    description: 'Sofistikerat lila tema',
    category: 'modern',
    tier: 'starter',
    preview: '/cv/midnight-purple.png',
    colors: {
      primary: '#7c3aed',
      secondary: '#8b5cf6',
      accent: '#a78bfa',
      background: '#1e1b4b',
      text: '#e0e7ff',
      muted: '#a5b4fc',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: false,
  },
  {
    id: 'cv-executive-navy',
    name: 'Executive Navy',
    description: 'Professionellt för ledare',
    category: 'executive',
    tier: 'starter',
    preview: '/cv/executive-navy.png',
    colors: {
      primary: '#1e3a8a',
      secondary: '#3b82f6',
      accent: '#60a5fa',
      background: '#ffffff',
      text: '#1e293b',
      muted: '#64748b',
    },
    fonts: { heading: 'Playfair Display, serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-swiss-style',
    name: 'Swiss Style',
    description: 'Inspirerat av schweizisk design',
    category: 'minimal',
    tier: 'starter',
    preview: '/cv/swiss-style.png',
    colors: {
      primary: '#dc2626',
      secondary: '#1f2937',
      accent: '#ef4444',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Helvetica, Arial, sans-serif', body: 'Helvetica, Arial, sans-serif' },
    layout: 'single-column',
    atsOptimized: true,
  },
  {
    id: 'cv-retro-vintage',
    name: 'Retro Vintage',
    description: 'Klassisk retro-känsla',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/retro-vintage.png',
    colors: {
      primary: '#92400e',
      secondary: '#b45309',
      accent: '#d97706',
      background: '#fef3c7',
      text: '#451a03',
      muted: '#78350f',
    },
    fonts: { heading: 'Playfair Display, serif', body: 'Lora, serif' },
    layout: 'classic',
    atsOptimized: false,
  },
  {
    id: 'cv-coral-reef',
    name: 'Coral Reef',
    description: 'Livfull korallrosa design',
    category: 'creative',
    tier: 'starter',
    preview: '/cv/coral-reef.png',
    colors: {
      primary: '#f43f5e',
      secondary: '#fb7185',
      accent: '#fda4af',
      background: '#fff1f2',
      text: '#881337',
      muted: '#be123c',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-slate-modern',
    name: 'Slate Modern',
    description: 'Modern grå elegans',
    category: 'professional',
    tier: 'starter',
    preview: '/cv/slate-modern.png',
    colors: {
      primary: '#475569',
      secondary: '#64748b',
      accent: '#94a3b8',
      background: '#ffffff',
      text: '#1e293b',
      muted: '#94a3b8',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-emerald-pro',
    name: 'Emerald Pro',
    description: 'Professionell smaragdgrön',
    category: 'professional',
    tier: 'starter',
    preview: '/cv/emerald-pro.png',
    colors: {
      primary: '#059669',
      secondary: '#10b981',
      accent: '#34d399',
      background: '#ffffff',
      text: '#064e3b',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },

  // =====================
  // PRO TIER (25 templates)
  // =====================
  {
    id: 'cv-executive',
    name: 'Executive',
    description: 'C-level och VD-profiler',
    category: 'executive',
    tier: 'pro',
    preview: '/cv/executive.png',
    colors: {
      primary: '#1e293b',
      secondary: '#334155',
      accent: '#475569',
      background: '#ffffff',
      text: '#0f172a',
      muted: '#64748b',
    },
    fonts: { heading: 'Cormorant Garamond, serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
    popular: true,
  },
  {
    id: 'cv-infographic',
    name: 'Infographic',
    description: 'Visuell infografik med diagram',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/infographic.png',
    colors: {
      primary: '#8b5cf6',
      secondary: '#a78bfa',
      accent: '#c4b5fd',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'infographic',
    atsOptimized: false,
    new: true,
  },
  {
    id: 'cv-timeline',
    name: 'Timeline',
    description: 'Tidslinje-fokuserad layout',
    category: 'modern',
    tier: 'pro',
    preview: '/cv/timeline.png',
    colors: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      accent: '#22d3ee',
      background: '#ffffff',
      text: '#164e63',
      muted: '#67e8f9',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'timeline',
    atsOptimized: true,
  },
  {
    id: 'cv-luxury-black',
    name: 'Luxury Black',
    description: 'Exklusiv svart med guld',
    category: 'executive',
    tier: 'pro',
    preview: '/cv/luxury-black.png',
    colors: {
      primary: '#d4af37',
      secondary: '#b8860b',
      accent: '#e6c75a',
      background: '#0a0a0a',
      text: '#fafafa',
      muted: '#a1a1aa',
    },
    fonts: { heading: 'Playfair Display, serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: false,
    popular: true,
  },
  {
    id: 'cv-architect',
    name: 'Architect',
    description: 'Ren geometrisk design',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/architect.png',
    colors: {
      primary: '#000000',
      secondary: '#333333',
      accent: '#666666',
      background: '#ffffff',
      text: '#000000',
      muted: '#999999',
    },
    fonts: { heading: 'Archivo, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-gradient-aurora',
    name: 'Gradient Aurora',
    description: 'Nordljus-inspirerade gradienter',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/gradient-aurora.png',
    colors: {
      primary: '#06b6d4',
      secondary: '#8b5cf6',
      accent: '#ec4899',
      background: '#0f172a',
      text: '#f8fafc',
      muted: '#94a3b8',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: false,
    new: true,
  },
  {
    id: 'cv-magazine',
    name: 'Magazine',
    description: 'Tidningsinspirerad layout',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/magazine.png',
    colors: {
      primary: '#1f2937',
      secondary: '#374151',
      accent: '#6b7280',
      background: '#f9fafb',
      text: '#111827',
      muted: '#6b7280',
    },
    fonts: { heading: 'Libre Baskerville, serif', body: 'Source Sans Pro, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-devops-crimson',
    name: 'DevOps Crimson',
    description: 'Inspirerat av saidborna.com',
    category: 'tech',
    tier: 'pro',
    preview: '/cv/devops-crimson.png',
    colors: {
      primary: '#ff4d4d',
      secondary: '#cc0000',
      accent: '#ff6666',
      background: '#0a0a0a',
      text: '#ffffff',
      muted: '#888888',
    },
    fonts: { heading: 'Bebas Neue, sans-serif', body: 'Space Grotesk, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
    popular: true,
  },
  {
    id: 'cv-minimalist-mono',
    name: 'Minimalist Mono',
    description: 'Ultra-ren monokrom design',
    category: 'minimal',
    tier: 'pro',
    preview: '/cv/minimalist-mono.png',
    colors: {
      primary: '#18181b',
      secondary: '#3f3f46',
      accent: '#71717a',
      background: '#ffffff',
      text: '#18181b',
      muted: '#a1a1aa',
    },
    fonts: { heading: 'IBM Plex Mono, monospace', body: 'IBM Plex Mono, monospace' },
    layout: 'single-column',
    atsOptimized: true,
  },
  {
    id: 'cv-creative-blocks',
    name: 'Creative Blocks',
    description: 'Modulär blockdesign',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/creative-blocks.png',
    colors: {
      primary: '#f472b6',
      secondary: '#38bdf8',
      accent: '#a3e635',
      background: '#ffffff',
      text: '#1e293b',
      muted: '#64748b',
    },
    fonts: { heading: 'Space Grotesk, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-japanese-minimal',
    name: 'Japanese Minimal',
    description: 'Japansk minimalism',
    category: 'minimal',
    tier: 'pro',
    preview: '/cv/japanese-minimal.png',
    colors: {
      primary: '#1f2937',
      secondary: '#374151',
      accent: '#dc2626',
      background: '#fafaf9',
      text: '#1c1917',
      muted: '#78716c',
    },
    fonts: { heading: 'Noto Serif, serif', body: 'Inter, sans-serif' },
    layout: 'single-column',
    atsOptimized: true,
  },
  {
    id: 'cv-tech-startup',
    name: 'Tech Startup',
    description: 'Modernt för tech-bolag',
    category: 'tech',
    tier: 'pro',
    preview: '/cv/tech-startup.png',
    colors: {
      primary: '#4f46e5',
      secondary: '#6366f1',
      accent: '#818cf8',
      background: '#ffffff',
      text: '#1e1b4b',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-finance-pro',
    name: 'Finance Pro',
    description: 'Professionellt för finans',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/finance-pro.png',
    colors: {
      primary: '#115e59',
      secondary: '#14b8a6',
      accent: '#2dd4bf',
      background: '#ffffff',
      text: '#134e4a',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-creative-agency',
    name: 'Creative Agency',
    description: 'Kreativt för byråer',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/creative-agency.png',
    colors: {
      primary: '#f59e0b',
      secondary: '#fbbf24',
      accent: '#fcd34d',
      background: '#1f2937',
      text: '#f3f4f6',
      muted: '#9ca3af',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-healthcare',
    name: 'Healthcare',
    description: 'Professionellt för vård',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/healthcare.png',
    colors: {
      primary: '#0d9488',
      secondary: '#14b8a6',
      accent: '#5eead4',
      background: '#f0fdfa',
      text: '#134e4a',
      muted: '#5eead4',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-legal',
    name: 'Legal',
    description: 'Formellt för jurister',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/legal.png',
    colors: {
      primary: '#1e3a5f',
      secondary: '#1e40af',
      accent: '#3b82f6',
      background: '#ffffff',
      text: '#1e293b',
      muted: '#64748b',
    },
    fonts: { heading: 'Libre Baskerville, serif', body: 'Georgia, serif' },
    layout: 'classic',
    atsOptimized: true,
  },
  {
    id: 'cv-media',
    name: 'Media',
    description: 'Kreativt för mediabranschen',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/media.png',
    colors: {
      primary: '#7c3aed',
      secondary: '#a78bfa',
      accent: '#c4b5fd',
      background: '#ffffff',
      text: '#1f2937',
      muted: '#6b7280',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-engineering',
    name: 'Engineering',
    description: 'Tekniskt för ingenjörer',
    category: 'tech',
    tier: 'pro',
    preview: '/cv/engineering.png',
    colors: {
      primary: '#0369a1',
      secondary: '#0284c7',
      accent: '#38bdf8',
      background: '#ffffff',
      text: '#0c4a6e',
      muted: '#64748b',
    },
    fonts: { heading: 'Roboto, sans-serif', body: 'Roboto, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-sales',
    name: 'Sales',
    description: 'Dynamiskt för säljare',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/sales.png',
    colors: {
      primary: '#ea580c',
      secondary: '#f97316',
      accent: '#fb923c',
      background: '#ffffff',
      text: '#1c1917',
      muted: '#78716c',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-marketing',
    name: 'Marketing',
    description: 'Kreativt för marknadsförare',
    category: 'creative',
    tier: 'pro',
    preview: '/cv/marketing.png',
    colors: {
      primary: '#db2777',
      secondary: '#ec4899',
      accent: '#f472b6',
      background: '#ffffff',
      text: '#831843',
      muted: '#9ca3af',
    },
    fonts: { heading: 'Poppins, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-education',
    name: 'Education',
    description: 'Professionellt för lärare',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/education.png',
    colors: {
      primary: '#7c2d12',
      secondary: '#c2410c',
      accent: '#ea580c',
      background: '#fffbeb',
      text: '#451a03',
      muted: '#78350f',
    },
    fonts: { heading: 'Merriweather, serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-nonprofit',
    name: 'Nonprofit',
    description: 'Professionellt för ideell sektor',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/nonprofit.png',
    colors: {
      primary: '#15803d',
      secondary: '#22c55e',
      accent: '#4ade80',
      background: '#f0fdf4',
      text: '#14532d',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: true,
  },
  {
    id: 'cv-freelancer',
    name: 'Freelancer',
    description: 'Personligt för frilansare',
    category: 'modern',
    tier: 'pro',
    preview: '/cv/freelancer.png',
    colors: {
      primary: '#0ea5e9',
      secondary: '#38bdf8',
      accent: '#7dd3fc',
      background: '#ffffff',
      text: '#0c4a6e',
      muted: '#64748b',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'sidebar',
    atsOptimized: false,
  },
  {
    id: 'cv-data-science',
    name: 'Data Science',
    description: 'Tekniskt för dataanalytiker',
    category: 'tech',
    tier: 'pro',
    preview: '/cv/data-science.png',
    colors: {
      primary: '#4f46e5',
      secondary: '#6366f1',
      accent: '#818cf8',
      background: '#0f172a',
      text: '#e2e8f0',
      muted: '#94a3b8',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'two-column',
    atsOptimized: false,
  },
  {
    id: 'cv-project-manager',
    name: 'Project Manager',
    description: 'Strukturerat för projektledare',
    category: 'professional',
    tier: 'pro',
    preview: '/cv/project-manager.png',
    colors: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      accent: '#22d3ee',
      background: '#ffffff',
      text: '#164e63',
      muted: '#6b7280',
    },
    fonts: { heading: 'Inter, sans-serif', body: 'Inter, sans-serif' },
    layout: 'timeline',
    atsOptimized: true,
  },
];

// Helper functions
export function getCVTemplateById(id: string): CVTemplateDefinition | undefined {
  return CV_TEMPLATES.find(t => t.id === id);
}

export function getCVTemplatesForTier(tier: 'free' | 'starter' | 'pro'): CVTemplateDefinition[] {
  if (tier === 'free') return CV_TEMPLATES.filter(t => t.tier === 'free');
  if (tier === 'starter') return CV_TEMPLATES.filter(t => t.tier === 'free' || t.tier === 'starter');
  return CV_TEMPLATES;
}

export function getCVTemplatesByCategory(category: CVTemplateDefinition['category']): CVTemplateDefinition[] {
  return CV_TEMPLATES.filter(t => t.category === category);
}

export function getPopularCVTemplates(limit: number = 10): CVTemplateDefinition[] {
  return CV_TEMPLATES.filter(t => t.popular).slice(0, limit);
}

export function searchCVTemplates(query: string): CVTemplateDefinition[] {
  const q = query.toLowerCase();
  return CV_TEMPLATES.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.category.includes(q)
  );
}

export default CV_TEMPLATES;
