// ============================================
// PORTFOLYO.SE - 100 Template Varianter
// Baserat på saidborna.com design
// ============================================

import {
    colorSchemes,
    animations,
    hoverEffects,
    backgroundPatterns,
    typographyStyles,
    layoutStyles,
    type ColorScheme,
    type Animation,
    type HoverEffect,
    type BackgroundPattern,
    type TypographyStyle,
    type LayoutStyle,
} from './effects';

export interface TemplateConfig {
    id: string;
    name: string;
    description: string;
    category: TemplateCategory;
    tier: 'free' | 'starter' | 'pro';  // Added tier for access control
    colorScheme: ColorScheme;
    typography: TypographyStyle;
    layout: LayoutStyle;
    backgroundPattern: BackgroundPattern;
    animations: {
        background: Animation;
        entrance: Animation;
        hover: HoverEffect;
    };
    features: TemplateFeature[];
    preview: string; // Preview image URL
    popularity: number;
    tags: string[];
}

export type TemplateCategory =
    | 'developer'
    | 'designer'
    | 'minimal'
    | 'creative'
    | 'professional'
    | 'bold'
    | 'elegant'
    | 'tech'
    | 'artistic'
    | 'startup';

export type TemplateFeature =
    | 'timeline'
    | 'stats'
    | 'techStack'
    | 'liaBanner'
    | 'cvModal'
    | 'projectGrid'
    | 'contactForm'
    | 'langSwitch'
    | 'darkMode'
    | 'floatingOrbs'
    | 'noiseTexture'
    | 'particlesBg'
    | 'gradientBg'
    | 'stickyNav'
    | 'scrollProgress'
    | 'cursorFollower';

// ============================================
// 100 TEMPLATE-DEFINITIONER
// ============================================

export const templates: TemplateConfig[] = [
    // =====================
    // DEVELOPER TEMPLATES (1-20)
    // =====================
    {
        id: 'dev-crimson-bold',
        name: 'DevOps Crimson',
        description: 'Original saidborna.com design - Bold crimson accent med floating orbs',
        category: 'developer',
        colorScheme: colorSchemes.crimson,
        typography: typographyStyles.modern,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInUp,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'stats', 'techStack', 'liaBanner', 'cvModal', 'projectGrid', 'floatingOrbs', 'noiseTexture', 'stickyNav'],
        preview: '/templates/dev-crimson-bold.png',
        popularity: 100,
        tags: ['devops', 'modern', 'bold', 'red'],
    },
    {
        id: 'dev-ocean-minimal',
        name: 'Deep Ocean',
        description: 'Mörkt blått tema med clean lines och subtila animationer',
        category: 'developer',
        colorScheme: colorSchemes.ocean,
        typography: typographyStyles.tech,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.grid,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.glow,
        },
        features: ['timeline', 'stats', 'techStack', 'projectGrid', 'stickyNav'],
        preview: '/templates/dev-ocean-minimal.png',
        popularity: 92,
        tags: ['developer', 'clean', 'blue', 'tech'],
    },
    {
        id: 'dev-emerald-matrix',
        name: 'Matrix Code',
        description: 'Hacker-inspirerat grönt tema med circuit board pattern',
        category: 'developer',
        colorScheme: colorSchemes.emerald,
        typography: typographyStyles.tech,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.circuitBoard,
        animations: {
            background: animations.particleFloat,
            entrance: animations.slideInLeft,
            hover: hoverEffects.borderAccent,
        },
        features: ['timeline', 'techStack', 'projectGrid', 'stickyNav', 'cursorFollower'],
        preview: '/templates/dev-emerald-matrix.png',
        popularity: 88,
        tags: ['hacker', 'matrix', 'green', 'tech'],
    },
    {
        id: 'dev-purple-cloud',
        name: 'Cloud Engineer',
        description: 'AWS/Azure inspirerat lila tema för cloud engineers',
        category: 'developer',
        colorScheme: colorSchemes.purple,
        typography: typographyStyles.modern,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInUp,
            hover: hoverEffects.depthPush,
        },
        features: ['timeline', 'stats', 'techStack', 'liaBanner', 'projectGrid', 'floatingOrbs'],
        preview: '/templates/dev-purple-cloud.png',
        popularity: 85,
        tags: ['cloud', 'aws', 'azure', 'purple'],
    },
    {
        id: 'dev-gold-senior',
        name: 'Senior Dev Gold',
        description: 'Prestigious guldton för erfarna utvecklare',
        category: 'developer',
        colorScheme: colorSchemes.gold,
        typography: typographyStyles.elegant,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.morphCard,
        },
        features: ['timeline', 'stats', 'techStack', 'cvModal', 'projectGrid', 'stickyNav'],
        preview: '/templates/dev-gold-senior.png',
        popularity: 82,
        tags: ['senior', 'prestigious', 'gold', 'experienced'],
    },
    {
        id: 'dev-mint-fresh',
        name: 'Fresh Start',
        description: 'Fräscht mint-tema för nyexaminerade utvecklare',
        category: 'developer',
        colorScheme: colorSchemes.mint,
        typography: typographyStyles.playful,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.waves,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.bounceIn,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'stats', 'techStack', 'liaBanner', 'projectGrid'],
        preview: '/templates/dev-mint-fresh.png',
        popularity: 78,
        tags: ['junior', 'fresh', 'mint', 'graduate'],
    },
    {
        id: 'dev-terminal-dark',
        name: 'Terminal Pro',
        description: 'Minimalistiskt terminal-inspirerat design',
        category: 'developer',
        colorScheme: {
            ...colorSchemes.emerald,
            id: 'terminal',
            name: 'Terminal',
            bgPrimary: '#000000',
            bgSecondary: '#0a0a0a',
            accent: '#00ff00',
        },
        typography: typographyStyles.tech,
        layout: layoutStyles.sidebar,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.borderAccent,
        },
        features: ['timeline', 'techStack', 'projectGrid', 'cursorFollower'],
        preview: '/templates/dev-terminal-dark.png',
        popularity: 90,
        tags: ['terminal', 'minimal', 'code', 'black'],
    },
    {
        id: 'dev-fullstack-split',
        name: 'Fullstack Split',
        description: 'Delad design för frontend/backend showcase',
        category: 'developer',
        colorScheme: colorSchemes.ocean,
        typography: typographyStyles.modern,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.diagonalLines,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.slideInRight,
            hover: hoverEffects.scale,
        },
        features: ['timeline', 'stats', 'techStack', 'projectGrid', 'stickyNav', 'scrollProgress'],
        preview: '/templates/dev-fullstack-split.png',
        popularity: 86,
        tags: ['fullstack', 'versatile', 'split'],
    },
    {
        id: 'dev-api-flow',
        name: 'API Flow',
        description: 'Backend-fokuserat tema med data flow visualisering',
        category: 'developer',
        colorScheme: colorSchemes.coral,
        typography: typographyStyles.tech,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.circuitBoard,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.glow,
        },
        features: ['timeline', 'techStack', 'projectGrid', 'stickyNav'],
        preview: '/templates/dev-api-flow.png',
        popularity: 75,
        tags: ['backend', 'api', 'data', 'coral'],
    },
    {
        id: 'dev-ml-gradient',
        name: 'ML Engineer',
        description: 'Gradient-rikt tema för AI/ML engineers',
        category: 'developer',
        colorScheme: colorSchemes.gradientAurora,
        typography: typographyStyles.modern,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.depthPush,
        },
        features: ['timeline', 'stats', 'techStack', 'projectGrid', 'floatingOrbs', 'gradientBg'],
        preview: '/templates/dev-ml-gradient.png',
        popularity: 88,
        tags: ['ml', 'ai', 'gradient', 'aurora'],
    },

    // =====================
    // DESIGNER TEMPLATES (21-40)
    // =====================
    {
        id: 'design-rose-elegant',
        name: 'Rose Elegance',
        description: 'Elegant rosa tema för UX/UI designers',
        category: 'designer',
        colorScheme: colorSchemes.rose,
        typography: typographyStyles.elegant,
        layout: layoutStyles.magazine,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInUp,
            hover: hoverEffects.morphCard,
        },
        features: ['projectGrid', 'stats', 'contactForm', 'stickyNav'],
        preview: '/templates/design-rose-elegant.png',
        popularity: 89,
        tags: ['designer', 'elegant', 'rose', 'ux'],
    },
    {
        id: 'design-minimal-white',
        name: 'Clean Canvas',
        description: 'Minimalistiskt vitt tema som låter portföljarbeten stå ut',
        category: 'designer',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.minimal,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.lift,
        },
        features: ['projectGrid', 'contactForm', 'stickyNav', 'darkMode'],
        preview: '/templates/design-minimal-white.png',
        popularity: 95,
        tags: ['minimal', 'clean', 'white', 'portfolio'],
    },
    {
        id: 'design-brutalist',
        name: 'Brutalist Bold',
        description: 'Anti-design brutalist estetik med stark typografi',
        category: 'designer',
        colorScheme: {
            ...colorSchemes.lightMinimal,
            id: 'brutalist',
            name: 'Brutalist',
            accent: '#ff0000',
        },
        typography: typographyStyles.creative,
        layout: layoutStyles.overlapping,
        backgroundPattern: backgroundPatterns.grid,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.rotateSubtle,
        },
        features: ['projectGrid', 'cursorFollower'],
        preview: '/templates/design-brutalist.png',
        popularity: 72,
        tags: ['brutalist', 'bold', 'anti-design', 'red'],
    },
    {
        id: 'design-editorial',
        name: 'Editorial Style',
        description: 'Tidnings-inspirerat layout för content creators',
        category: 'designer',
        colorScheme: colorSchemes.lightWarm,
        typography: typographyStyles.editorial,
        layout: layoutStyles.magazine,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.lift,
        },
        features: ['projectGrid', 'contactForm', 'stickyNav'],
        preview: '/templates/design-editorial.png',
        popularity: 80,
        tags: ['editorial', 'magazine', 'warm', 'content'],
    },
    {
        id: 'design-3d-creative',
        name: '3D Creative',
        description: 'Tilt-effekter och 3D-känsla för motion designers',
        category: 'designer',
        colorScheme: colorSchemes.gradientSunset,
        typography: typographyStyles.creative,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInScale,
            hover: hoverEffects.tilt,
        },
        features: ['projectGrid', 'cursorFollower', 'floatingOrbs', 'gradientBg'],
        preview: '/templates/design-3d-creative.png',
        popularity: 85,
        tags: ['3d', 'motion', 'sunset', 'creative'],
    },
    {
        id: 'design-pastel-soft',
        name: 'Pastel Dreams',
        description: 'Mjuka pasteller för illustration portfolios',
        category: 'designer',
        colorScheme: {
            ...colorSchemes.lightCool,
            id: 'pastel',
            name: 'Pastel',
            bgPrimary: '#fef7ff',
            bgSecondary: '#f5f0ff',
            accent: '#c084fc',
        },
        typography: typographyStyles.playful,
        layout: layoutStyles.stacked,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.scale,
        },
        features: ['projectGrid', 'contactForm'],
        preview: '/templates/design-pastel-soft.png',
        popularity: 76,
        tags: ['pastel', 'soft', 'illustration', 'purple'],
    },
    {
        id: 'design-mono-contrast',
        name: 'High Contrast',
        description: 'Stark svart-vit kontrast för grafiska designers',
        category: 'designer',
        colorScheme: {
            ...colorSchemes.lightMinimal,
            id: 'monoContrast',
            name: 'Mono Contrast',
            bgPrimary: '#ffffff',
            bgSecondary: '#000000',
            textPrimary: '#000000',
        },
        typography: typographyStyles.modern,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInRight,
            hover: hoverEffects.borderAccent,
        },
        features: ['projectGrid', 'stickyNav', 'darkMode'],
        preview: '/templates/design-mono-contrast.png',
        popularity: 83,
        tags: ['mono', 'contrast', 'black', 'white'],
    },
    {
        id: 'design-brand-focus',
        name: 'Brand Designer',
        description: 'Fokus på branding-arbete med logotype showcase',
        category: 'designer',
        colorScheme: colorSchemes.gold,
        typography: typographyStyles.classic,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.morphCard,
        },
        features: ['projectGrid', 'stats', 'contactForm', 'stickyNav'],
        preview: '/templates/design-brand-focus.png',
        popularity: 79,
        tags: ['branding', 'logo', 'gold', 'classic'],
    },
    {
        id: 'design-photo-grid',
        name: 'Photo Grid',
        description: 'Masonry-layout för fotografer',
        category: 'designer',
        colorScheme: colorSchemes.crimson,
        typography: typographyStyles.minimal,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.scale,
        },
        features: ['projectGrid', 'contactForm'],
        preview: '/templates/design-photo-grid.png',
        popularity: 87,
        tags: ['photography', 'grid', 'gallery', 'minimal'],
    },
    {
        id: 'design-product-showcase',
        name: 'Product Designer',
        description: 'Case study-fokuserat för product designers',
        category: 'designer',
        colorScheme: colorSchemes.lightCool,
        typography: typographyStyles.modern,
        layout: layoutStyles.sidebar,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'projectGrid', 'stats', 'contactForm', 'stickyNav'],
        preview: '/templates/design-product-showcase.png',
        popularity: 91,
        tags: ['product', 'case-study', 'ux', 'ui'],
    },

    // =====================
    // MINIMAL TEMPLATES (41-55)
    // =====================
    {
        id: 'min-zen-white',
        name: 'Zen White',
        description: 'Ultra-minimalistiskt zen-inspirerat tema',
        category: 'minimal',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.minimal,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.lift,
        },
        features: ['projectGrid', 'contactForm', 'darkMode'],
        preview: '/templates/min-zen-white.png',
        popularity: 94,
        tags: ['zen', 'minimal', 'white', 'clean'],
    },
    {
        id: 'min-dark-void',
        name: 'Dark Void',
        description: 'Mörk minimal med fokus på whitespace',
        category: 'minimal',
        colorScheme: {
            ...colorSchemes.crimson,
            id: 'darkVoid',
            name: 'Dark Void',
            accent: '#ffffff',
            accentGlow: 'rgba(255, 255, 255, 0.1)',
        },
        typography: typographyStyles.minimal,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.glow,
        },
        features: ['projectGrid', 'contactForm', 'stickyNav'],
        preview: '/templates/min-dark-void.png',
        popularity: 88,
        tags: ['dark', 'void', 'minimal', 'monochrome'],
    },
    {
        id: 'min-single-accent',
        name: 'Single Accent',
        description: 'En färg accent mot neutral bakgrund',
        category: 'minimal',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.modern,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.borderAccent,
        },
        features: ['projectGrid', 'stats', 'contactForm', 'stickyNav'],
        preview: '/templates/min-single-accent.png',
        popularity: 82,
        tags: ['accent', 'single-color', 'minimal'],
    },
    {
        id: 'min-text-only',
        name: 'Type Only',
        description: 'Fokus 100% på typografi, inga bilder',
        category: 'minimal',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.editorial,
        layout: layoutStyles.stacked,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'stats', 'contactForm'],
        preview: '/templates/min-text-only.png',
        popularity: 70,
        tags: ['typography', 'text', 'no-images'],
    },
    {
        id: 'min-grid-system',
        name: 'Grid System',
        description: 'Strikt grid-baserad layout',
        category: 'minimal',
        colorScheme: colorSchemes.lightCool,
        typography: typographyStyles.tech,
        layout: layoutStyles.sidebar,
        backgroundPattern: backgroundPatterns.grid,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInRight,
            hover: hoverEffects.scale,
        },
        features: ['projectGrid', 'stats', 'techStack', 'stickyNav'],
        preview: '/templates/min-grid-system.png',
        popularity: 77,
        tags: ['grid', 'systematic', 'structured'],
    },

    // =====================
    // PROFESSIONAL TEMPLATES (56-70)
    // =====================
    {
        id: 'pro-corporate-blue',
        name: 'Corporate Blue',
        description: 'Professionellt blått tema för enterprise-miljöer',
        category: 'professional',
        colorScheme: colorSchemes.ocean,
        typography: typographyStyles.classic,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'stats', 'techStack', 'cvModal', 'liaBanner', 'contactForm', 'stickyNav'],
        preview: '/templates/pro-corporate-blue.png',
        popularity: 93,
        tags: ['corporate', 'professional', 'blue', 'enterprise'],
    },
    {
        id: 'pro-consultant',
        name: 'Senior Consultant',
        description: 'Förtroendeingivande design för konsulter',
        category: 'professional',
        colorScheme: colorSchemes.gold,
        typography: typographyStyles.elegant,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.morphCard,
        },
        features: ['timeline', 'stats', 'cvModal', 'contactForm', 'stickyNav'],
        preview: '/templates/pro-consultant.png',
        popularity: 86,
        tags: ['consultant', 'senior', 'gold', 'trust'],
    },
    {
        id: 'pro-executive',
        name: 'Executive Level',
        description: 'C-level och executive profiler',
        category: 'professional',
        colorScheme: {
            ...colorSchemes.crimson,
            id: 'executive',
            name: 'Executive',
            bgPrimary: '#0c0c0c',
            accent: '#c9a96e',
            accentGlow: 'rgba(201, 169, 110, 0.3)',
        },
        typography: typographyStyles.elegant,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.glow,
        },
        features: ['timeline', 'stats', 'cvModal', 'contactForm', 'stickyNav'],
        preview: '/templates/pro-executive.png',
        popularity: 75,
        tags: ['executive', 'luxury', 'gold', 'leadership'],
    },
    {
        id: 'pro-startup-cto',
        name: 'Startup CTO',
        description: 'Modern tech-leadare i startup-miljö',
        category: 'professional',
        colorScheme: colorSchemes.purple,
        typography: typographyStyles.modern,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInUp,
            hover: hoverEffects.lift,
        },
        features: ['timeline', 'stats', 'techStack', 'projectGrid', 'liaBanner', 'stickyNav', 'floatingOrbs'],
        preview: '/templates/pro-startup-cto.png',
        popularity: 89,
        tags: ['startup', 'cto', 'tech', 'leadership'],
    },
    {
        id: 'pro-cv-first',
        name: 'CV Focused',
        description: 'CV och erfarenhet i fokus',
        category: 'professional',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.classic,
        layout: layoutStyles.sidebar,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.borderAccent,
        },
        features: ['timeline', 'stats', 'cvModal', 'contactForm', 'stickyNav', 'darkMode'],
        preview: '/templates/pro-cv-first.png',
        popularity: 91,
        tags: ['cv', 'resume', 'experience', 'formal'],
    },

    // =====================
    // BOLD TEMPLATES (71-80)
    // =====================
    {
        id: 'bold-neon-pink',
        name: 'Neon Pink',
        description: 'Stark neon-rosa för att sticka ut',
        category: 'bold',
        colorScheme: {
            ...colorSchemes.rose,
            id: 'neonPink',
            name: 'Neon Pink',
            accent: '#ff00ff',
            accentGlow: 'rgba(255, 0, 255, 0.4)',
        },
        typography: typographyStyles.creative,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.bounceIn,
            hover: hoverEffects.glow,
        },
        features: ['projectGrid', 'cursorFollower', 'floatingOrbs', 'noiseTexture'],
        preview: '/templates/bold-neon-pink.png',
        popularity: 78,
        tags: ['neon', 'pink', 'bold', 'attention'],
    },
    {
        id: 'bold-cyber-yellow',
        name: 'Cyber Yellow',
        description: 'Cyberpunk-inspirerat gult tema',
        category: 'bold',
        colorScheme: {
            ...colorSchemes.gold,
            id: 'cyberYellow',
            name: 'Cyber Yellow',
            bgPrimary: '#0a0a0a',
            accent: '#ffff00',
            accentGlow: 'rgba(255, 255, 0, 0.4)',
        },
        typography: typographyStyles.tech,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.circuitBoard,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInRight,
            hover: hoverEffects.borderAccent,
        },
        features: ['projectGrid', 'techStack', 'cursorFollower'],
        preview: '/templates/bold-cyber-yellow.png',
        popularity: 74,
        tags: ['cyber', 'yellow', 'punk', 'edgy'],
    },
    {
        id: 'bold-gradient-chaos',
        name: 'Gradient Chaos',
        description: 'Vilda gradienter för kreativa själar',
        category: 'bold',
        colorScheme: colorSchemes.gradientSunset,
        typography: typographyStyles.creative,
        layout: layoutStyles.overlapping,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.tilt,
        },
        features: ['projectGrid', 'floatingOrbs', 'gradientBg', 'cursorFollower'],
        preview: '/templates/bold-gradient-chaos.png',
        popularity: 70,
        tags: ['gradient', 'chaos', 'creative', 'wild'],
    },
    {
        id: 'bold-retro-orange',
        name: 'Retro Orange',
        description: '70-tals inspirerat retro-tema',
        category: 'bold',
        colorScheme: {
            ...colorSchemes.lightWarm,
            id: 'retroOrange',
            name: 'Retro Orange',
            bgPrimary: '#2d1b0e',
            bgSecondary: '#3d2815',
            bgCard: '#4d3520',
            accent: '#ff6600',
            textPrimary: '#fff5e6',
        },
        typography: typographyStyles.playful,
        layout: layoutStyles.stacked,
        backgroundPattern: backgroundPatterns.diagonalLines,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.rotateSubtle,
        },
        features: ['projectGrid', 'stats', 'contactForm'],
        preview: '/templates/bold-retro-orange.png',
        popularity: 68,
        tags: ['retro', '70s', 'orange', 'vintage'],
    },
    {
        id: 'bold-maximalist',
        name: 'Maximalist Mix',
        description: 'Allt på max - färger, animationer, effekter',
        category: 'bold',
        colorScheme: colorSchemes.gradientAurora,
        typography: typographyStyles.creative,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.bounceIn,
            hover: hoverEffects.depthPush,
        },
        features: ['timeline', 'stats', 'techStack', 'projectGrid', 'floatingOrbs', 'noiseTexture', 'particlesBg', 'cursorFollower', 'scrollProgress'],
        preview: '/templates/bold-maximalist.png',
        popularity: 65,
        tags: ['maximalist', 'everything', 'effects', 'wild'],
    },

    // =====================
    // ELEGANT TEMPLATES (81-90)
    // =====================
    {
        id: 'elegant-champagne',
        name: 'Champagne Gold',
        description: 'Lyxigt champagnefärgat tema',
        category: 'elegant',
        colorScheme: {
            ...colorSchemes.gold,
            id: 'champagne',
            name: 'Champagne',
            bgPrimary: '#1a1612',
            accent: '#d4af37',
            accentGlow: 'rgba(212, 175, 55, 0.2)',
        },
        typography: typographyStyles.elegant,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.morphCard,
        },
        features: ['timeline', 'stats', 'cvModal', 'contactForm', 'stickyNav'],
        preview: '/templates/elegant-champagne.png',
        popularity: 84,
        tags: ['champagne', 'luxury', 'gold', 'elegant'],
    },
    {
        id: 'elegant-marble',
        name: 'Marble Luxe',
        description: 'Marmor-inspirerat ljust tema',
        category: 'elegant',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.elegant,
        layout: layoutStyles.magazine,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.lift,
        },
        features: ['projectGrid', 'stats', 'contactForm', 'stickyNav'],
        preview: '/templates/elegant-marble.png',
        popularity: 81,
        tags: ['marble', 'luxe', 'white', 'sophisticated'],
    },
    {
        id: 'elegant-midnight-blue',
        name: 'Midnight Blue',
        description: 'Djupt midnattsblått för sofistikerad look',
        category: 'elegant',
        colorScheme: {
            ...colorSchemes.ocean,
            id: 'midnightBlue',
            name: 'Midnight Blue',
            bgPrimary: '#0a0e1a',
            bgSecondary: '#0d1224',
            accent: '#8ba4ff',
        },
        typography: typographyStyles.elegant,
        layout: layoutStyles.splitHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.slideInLeft,
            hover: hoverEffects.glow,
        },
        features: ['timeline', 'stats', 'projectGrid', 'contactForm', 'stickyNav', 'floatingOrbs'],
        preview: '/templates/elegant-midnight-blue.png',
        popularity: 86,
        tags: ['midnight', 'blue', 'sophisticated', 'deep'],
    },
    {
        id: 'elegant-wine',
        name: 'Burgundy Wine',
        description: 'Vinrött elegant tema',
        category: 'elegant',
        colorScheme: {
            ...colorSchemes.rose,
            id: 'burgundy',
            name: 'Burgundy',
            bgPrimary: '#1a0a0e',
            bgSecondary: '#240d14',
            bgCard: '#2e1219',
            accent: '#8b2942',
        },
        typography: typographyStyles.elegant,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.morphCard,
        },
        features: ['timeline', 'cvModal', 'contactForm', 'stickyNav'],
        preview: '/templates/elegant-wine.png',
        popularity: 77,
        tags: ['burgundy', 'wine', 'sophisticated', 'rich'],
    },
    {
        id: 'elegant-pearl',
        name: 'Pearl White',
        description: 'Skimrande pärlvitt för tidlös elegans',
        category: 'elegant',
        colorScheme: {
            ...colorSchemes.lightMinimal,
            id: 'pearl',
            name: 'Pearl',
            bgPrimary: '#fafaf8',
            bgSecondary: '#f5f5f0',
            accent: '#1a1a1a',
        },
        typography: typographyStyles.elegant,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.shimmer,
            entrance: animations.fadeInScale,
            hover: hoverEffects.scale,
        },
        features: ['projectGrid', 'contactForm', 'stickyNav', 'darkMode'],
        preview: '/templates/elegant-pearl.png',
        popularity: 83,
        tags: ['pearl', 'white', 'timeless', 'refined'],
    },

    // =====================
    // CREATIVE TEMPLATES (91-100)
    // =====================
    {
        id: 'creative-glitch',
        name: 'Glitch Art',
        description: 'Glitch-effekter för experimentella designers',
        category: 'creative',
        colorScheme: colorSchemes.crimson,
        typography: typographyStyles.tech,
        layout: layoutStyles.overlapping,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.rotateSubtle,
        },
        features: ['projectGrid', 'cursorFollower', 'noiseTexture'],
        preview: '/templates/creative-glitch.png',
        popularity: 71,
        tags: ['glitch', 'experimental', 'art', 'edgy'],
    },
    {
        id: 'creative-comic',
        name: 'Comic Pop',
        description: 'Serietidnings-inspirerad pop art stil',
        category: 'creative',
        colorScheme: {
            ...colorSchemes.lightMinimal,
            id: 'comicPop',
            name: 'Comic Pop',
            bgPrimary: '#fff9e6',
            accent: '#ff3366',
            textPrimary: '#1a1a2e',
        },
        typography: typographyStyles.playful,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.scale,
        },
        features: ['projectGrid', 'stats'],
        preview: '/templates/creative-comic.png',
        popularity: 66,
        tags: ['comic', 'pop', 'fun', 'colorful'],
    },
    {
        id: 'creative-abstract',
        name: 'Abstract Art',
        description: 'Abstrakt konst-inspirerat för konstnärer',
        category: 'creative',
        colorScheme: colorSchemes.gradientSunset,
        typography: typographyStyles.creative,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.waves,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInScale,
            hover: hoverEffects.tilt,
        },
        features: ['projectGrid', 'floatingOrbs', 'gradientBg'],
        preview: '/templates/creative-abstract.png',
        popularity: 73,
        tags: ['abstract', 'art', 'colorful', 'artistic'],
    },
    {
        id: 'creative-neon-noir',
        name: 'Neon Noir',
        description: 'Film noir möter neon för fotografer',
        category: 'creative',
        colorScheme: {
            ...colorSchemes.crimson,
            id: 'neonNoir',
            name: 'Neon Noir',
            bgPrimary: '#050505',
            bgSecondary: '#0a0a0a',
            accent: '#00ffff',
            accentGlow: 'rgba(0, 255, 255, 0.4)',
        },
        typography: typographyStyles.modern,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.glow,
        },
        features: ['projectGrid', 'noiseTexture'],
        preview: '/templates/creative-neon-noir.png',
        popularity: 79,
        tags: ['noir', 'neon', 'cinematic', 'cyan'],
    },
    {
        id: 'creative-handdrawn',
        name: 'Hand Drawn',
        description: 'Handritad stil för illustratörer',
        category: 'creative',
        colorScheme: colorSchemes.lightWarm,
        typography: typographyStyles.playful,
        layout: layoutStyles.stacked,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInUp,
            hover: hoverEffects.rotateSubtle,
        },
        features: ['projectGrid', 'contactForm'],
        preview: '/templates/creative-handdrawn.png',
        popularity: 69,
        tags: ['handdrawn', 'sketch', 'illustration', 'warm'],
    },
    {
        id: 'creative-vaporwave',
        name: 'Vaporwave',
        description: '90-tals retro-futurism estetik',
        category: 'creative',
        colorScheme: {
            ...colorSchemes.purple,
            id: 'vaporwave',
            name: 'Vaporwave',
            bgPrimary: '#1a0a2e',
            accent: '#ff71ce',
            accentGlow: 'rgba(255, 113, 206, 0.4)',
        },
        typography: typographyStyles.tech,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.grid,
        animations: {
            background: animations.gradientShift,
            entrance: animations.fadeInScale,
            hover: hoverEffects.glow,
        },
        features: ['projectGrid', 'techStack', 'cursorFollower'],
        preview: '/templates/creative-vaporwave.png',
        popularity: 72,
        tags: ['vaporwave', 'retro', '90s', 'pink'],
    },
    {
        id: 'creative-holographic',
        name: 'Holographic',
        description: 'Holografisk regnbågseffekt',
        category: 'creative',
        colorScheme: colorSchemes.gradientAurora,
        typography: typographyStyles.modern,
        layout: layoutStyles.centeredHero,
        backgroundPattern: backgroundPatterns.noise,
        animations: {
            background: animations.gradientShift,
            entrance: animations.bounceIn,
            hover: hoverEffects.depthPush,
        },
        features: ['projectGrid', 'floatingOrbs', 'gradientBg', 'cursorFollower'],
        preview: '/templates/creative-holographic.png',
        popularity: 76,
        tags: ['holographic', 'rainbow', 'iridescent', 'modern'],
    },
    {
        id: 'creative-collage',
        name: 'Digital Collage',
        description: 'Collage-stil för mixed media artists',
        category: 'creative',
        colorScheme: colorSchemes.lightMinimal,
        typography: typographyStyles.creative,
        layout: layoutStyles.overlapping,
        backgroundPattern: backgroundPatterns.dots,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInRight,
            hover: hoverEffects.tilt,
        },
        features: ['projectGrid'],
        preview: '/templates/creative-collage.png',
        popularity: 67,
        tags: ['collage', 'mixed-media', 'artistic', 'experimental'],
    },
    {
        id: 'creative-synthwave',
        name: 'Synthwave',
        description: '80-tals synthwave för musik/tech creators',
        category: 'creative',
        colorScheme: {
            ...colorSchemes.gradientSunset,
            id: 'synthwave',
            name: 'Synthwave',
            bgPrimary: '#0f0a1a',
            accent: '#f72585',
            accentGlow: 'rgba(247, 37, 133, 0.4)',
        },
        typography: typographyStyles.modern,
        layout: layoutStyles.fullscreenImage,
        backgroundPattern: backgroundPatterns.grid,
        animations: {
            background: animations.floatingOrbs,
            entrance: animations.fadeInScale,
            hover: hoverEffects.glow,
        },
        features: ['projectGrid', 'techStack', 'floatingOrbs'],
        preview: '/templates/creative-synthwave.png',
        popularity: 80,
        tags: ['synthwave', '80s', 'retro', 'neon'],
    },
    {
        id: 'creative-bauhaus',
        name: 'Bauhaus Modern',
        description: 'Bauhaus-inspirerad geometrisk design',
        category: 'creative',
        colorScheme: {
            ...colorSchemes.lightMinimal,
            id: 'bauhaus',
            name: 'Bauhaus',
            bgPrimary: '#f5f0e1',
            accent: '#e63946',
            textPrimary: '#1d3557',
        },
        typography: typographyStyles.modern,
        layout: layoutStyles.asymmetric,
        backgroundPattern: backgroundPatterns.none,
        animations: {
            background: animations.gradientShift,
            entrance: animations.slideInLeft,
            hover: hoverEffects.borderAccent,
        },
        features: ['projectGrid', 'stats'],
        preview: '/templates/creative-bauhaus.png',
        popularity: 74,
        tags: ['bauhaus', 'geometric', 'modernist', 'classic'],
    },
];

// Hjälpfunktioner
export const getTemplateById = (id: string): TemplateConfig | undefined =>
    templates.find(t => t.id === id);

export const getTemplatesByCategory = (category: TemplateCategory): TemplateConfig[] =>
    templates.filter(t => t.category === category);

export const getTemplatesByFeature = (feature: TemplateFeature): TemplateConfig[] =>
    templates.filter(t => t.features.includes(feature));

export const getTemplatesByTag = (tag: string): TemplateConfig[] =>
    templates.filter(t => t.tags.includes(tag.toLowerCase()));

export const getPopularTemplates = (limit: number = 10): TemplateConfig[] =>
    [...templates].sort((a, b) => b.popularity - a.popularity).slice(0, limit);

export const searchTemplates = (query: string): TemplateConfig[] => {
    const q = query.toLowerCase();
    return templates.filter(t =>
        t.name.toLowerCase().includes(q) ||
        t.description.toLowerCase().includes(q) ||
        t.tags.some(tag => tag.includes(q)) ||
        t.category.includes(q)
    );
};

// Kategoribeskrivningar
export const categoryDescriptions: Record<TemplateCategory, { name: string; description: string; icon: string }> = {
    developer: { name: 'Developer', description: 'För utvecklare och DevOps engineers', icon: '💻' },
    designer: { name: 'Designer', description: 'För UX/UI och grafiska designers', icon: '🎨' },
    minimal: { name: 'Minimal', description: 'Rent och enkelt med fokus på innehåll', icon: '✨' },
    creative: { name: 'Creative', description: 'Experimentella och konstnärliga designer', icon: '🎭' },
    professional: { name: 'Professional', description: 'Seriöst och förtroendeingivande', icon: '💼' },
    bold: { name: 'Bold', description: 'Starka färger och uppmärksamhetsfångande', icon: '🔥' },
    elegant: { name: 'Elegant', description: 'Sofistikerat och tidlöst', icon: '👑' },
    tech: { name: 'Tech', description: 'Modernt och tech-fokuserat', icon: '🚀' },
    artistic: { name: 'Artistic', description: 'För konstnärer och fotografer', icon: '🖼️' },
    startup: { name: 'Startup', description: 'Dynamiskt och innovativt', icon: '⚡' },
};

export default templates;
